### ISSUE TITLE
Issues with Bitcoin Core 0.9.3 block chain. Does it work anymore?

### ISSUE THREAD

**Issue by e5faf2** [jtauber/blockchain#1]
Im expecting problems with block chain from Bitcoin Core v 0.9.3.
First issue in assert in line 156, its not passing.

```
assert self.get_uint32() == 0xD9B4BEF9  # magic network id
```

Another issue (if I comment previous assert) is not expected opcode:

```
BLOCK 43054 b'14508459b221041eab257d2baaa7459775ba748246c8403609eb708f0e57e74b'
unknown opcode 101
Traceback (most recent call last):
  File "./blockchain.py", line 227, in <module>
    for block_num, block in enumerate(block_chain.blocks()):
  File "./blockchain.py", line 74, in blocks
    yield self.parse_block()
  File "./blockchain.py", line 180, in parse_block
    self.parse_transaction() for i in range(transaction_count)
  File "./blockchain.py", line 180, in <listcomp>
    self.parse_transaction() for i in range(transaction_count)
  File "./blockchain.py", line 193, in parse_transaction
    "inputs": self.parse_inputs(),
  File "./blockchain.py", line 210, in parse_inputs
    } for i in range(count)]
  File "./blockchain.py", line 210, in <listcomp>
    } for i in range(count)]
  File "./blockchain.py", line 149, in get_script
    raise ValueError
ValueError
```

Thanks.

**Comment by jtauber** [comment]
Any `unknown opcode` errors will just be because I haven't implemented many opcodes. It's odd that the magic id would have changed, though. I haven't look at this for a while to know if there have been any format changes.

**Comment by BaoBaoJianqiang** [comment]
could you please give a demo file to operate?

**Comment by adamr2** [comment]
Did you solve this?
I'm getting the same invalid magic number and hash:
14508459b221041eab257d2baaa7459775ba748246c8403609eb708f0e57e74b
in my own parser
Thanks
